#!/bin/bash

# Move to the Ubuntu folder
cd Linux

cd Ubuntu_18_04

# Run the Ubuntu 18:04 container
path=`pwd`
docker run --rm -ti -p 8888:8888 -v $path/data:/root inferpy:ubuntu18_04 /bin/bash

# Move to the folder where are the tests
cd InferPy

# Execute the tests
python -m pytest tests
