FROM ubuntu:18.04

MAINTAINER Rafael Cabañas <rcabanas@decsai.ugr.es>

RUN apt-get update ; \
	apt-get install -y software-properties-common
	
RUN apt-get update ;

	
RUN git clone -b develop https://github.com/PGM-Lab/InferPy.git


WORKDIR /home/root/






    





