
FROM fedora:29
MAINTAINER Juan Jesús Ojeda <juanje.ojeda@ual.es>

RUN pwd
RUN whoami

# Set current working directory
WORKDIR /home/root/


# Clone the branch develop from the repository	
#RUN git clone -b develop https://github.com/PGM-Lab/InferPy.git

# Install the requirements
#RUN cd InferPy ; \
#	pip3 install --upgrade pip; \
#	pip3 install --user -r requirements.txt ; \
#	pip3 install -U pytest 










    














    





